services:
  app:
    build: .
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "80"
    networks:
      - default
      - web

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
    depends_on:
      - database  
    expose:
      - "80"
    networks:
      - default
      - web   
volumes:
  mysql_data:
networks:
  web:
    external: true